name: Creating an application build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Archive packaging
        run: tar -cvzf build.tar.gz build/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist.tar.gz
